# Generated by Django 5.0.2 on 2024-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('rollbacked', 'Rollbacked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='occupancy_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('market', 'season', 'year')},
        ),
    ]
