# Generated by Django 5.0.2 on 2024-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0004_remove_report_comment_remove_report_comment_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='component_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
