# Generated by Django 5.0.2 on 2024-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0005_alter_reportrecord_component_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='season',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
