# Generated by Django 5.0.2 on 2024-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0007_alter_report_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
