# Generated by Django 5.0.2 on 2024-03-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0008_report_forwarded_at_report_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
