# Generated by Django 5.0.2 on 2024-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0009_report_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('rollbacked', 'Rollbacked')], default='pending', max_length=255),
        ),
    ]
