# Generated by Django 5.0.2 on 2024-03-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0010_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('rollbacked', 'Rollbacked')], default='pending', max_length=30),
        ),
    ]
