# Generated by Django 5.0.2 on 2024-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0011_alter_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('total_number_places_available', models.IntegerField()),
            ],
            options={
                'db_table': 'component',
            },
        ),
    ]
