# Generated by Django 5.0.2 on 2024-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketrecord', '0013_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='observation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
